apiRules:
    
    # Don't include samples
  - exclude:
      uidRegex: ^Samples
      type: Namespace

  # Don't include tests
  - exclude:
      uidRegex: ^Tests
      type: Namespace

  # Don't include editor scripts
  - exclude:
      uidRegex: ^LDtkUnity\.Editor
      type: Namespace

  - exclude:
      hasAttribute:
        uid: System.ComponentModel.EditorBrowsableAttribute
        ctorArguments:
          - System.ComponentModel.EditorBrowsableState.Never