apiRules:
    
    # Don't include samples
  - exclude:
      uidRegex: ^Samples
      type: Namespace

  # Don't include tests
  - exclude:
      uidRegex: ^Tests
      type: Namespace

  # Don't include editor scripts
  - exclude:
      uidRegex: ^LDtkUnity\.Editor
      type: Namespace
      
  # Exclude Types with Unity's ExcludeFromDocs
  - exclude:
      hasAttribute:
        type: Type
        uid: UnityEngine.Internal.ExcludeFromDocsAttribute
        
  # Exclude Members with Unity's ExcludeFromDocs
  - exclude:
      hasAttribute:
        type: Member
        uid: UnityEngine.Internal.ExcludeFromDocsAttribute

  # Exclude the schema json data
  - exclude:
      hasAttribute:
        type: Property
        uid: Newtonsoft.Json.JsonPropertyAttribute
