name: Main Build Actions

on: [push, pull_request]

jobs:

    Tests:
        name: Test-${{ matrix.testMode }}-${{ matrix.unityVersion }}
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                testMode:
                    #- playmode
                    - editmode
                unityVersion:
                    - 2019.3.0f6
                    - 2019.4.0f1
                    #- 2020.1.0f1 # Had issue authenticating license
                    #- 2020.2.0f1 # Had issue with test package not covering for GameCore xbox
                    - 2020.3.0f1
                    - 2021.1.0f1
                    - 2021.2.0f1
        
        steps:
        
            #Checkout
            - uses: actions/checkout@v2
              with:
                  lfs: true
                
            #Cache
            - uses: actions/cache@v2
              with:
                  path: ${{ matrix.projectPath }}-${{ matrix.unityVersion }}/Library
                  key: Library-${{ matrix.projectPath }}-${{ matrix.unityVersion }}
                  restore-keys: Library-
                
            #Test Runner
            - uses: game-ci/unity-test-runner@v2
              id: tests
              env:
                  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
              with:
                  projectPath: ${{ matrix.projectPath }}
                  testMode: ${{ matrix.testMode }}
                  artifactsPath: ${{ matrix.testMode }}-artifacts
                  githubToken: ${{ secrets.GITHUB_TOKEN }}
                  checkName: Test results ${{ matrix.testMode }}-${{ matrix.unityVersion }}
                  unityVersion: ${{ matrix.unityVersion }}
        
            #Artifact
            - uses: actions/upload-artifact@v2
              if: always()
              with:
                  name: Test results for ${{ matrix.testMode }}-${{ matrix.unityVersion }}
                  path: ${{ steps.tests.outputs.artifactsPath }}
      
    #BUILD
    Builds:
        name: Build-${{ matrix.targetPlatform }}-${{ matrix.unityVersion }}
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                targetPlatform:
                    - StandaloneWindows
                    #- WebGL
                unityVersion:
                    - 2019.3.0f6
                    - 2019.4.0f1
                    #- 2020.1.0f1 # Had issue authenticating license
                    #- 2020.2.0f1 # Had issue with test package not covering for GameCore xbox
                    - 2020.3.0f1
                    - 2021.1.0f1
                    - 2021.2.0f1
              
        steps:
        
            #Checkout
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0
                  lfs: true
                  
            #Cache
            - uses: actions/cache@v2
              with:
                  path: Library
                  key: Library-${{ matrix.targetPlatform }}-${{ matrix.unityVersion }}
                  restore-keys: Library-
                  
            #Build
            - uses: game-ci/unity-builder@v2
              env:
                  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
              with:
                  targetPlatform: ${{ matrix.targetPlatform }}
                  unityVersion: ${{ matrix.unityVersion }}
                  
            #Artifact
            - uses: actions/upload-artifact@v2
              with:
                  name: Build-${{ matrix.targetPlatform }}-${{ matrix.unityVersion }}
                  path: build/${{ matrix.targetPlatform }}